export const EDIT_TEMPLATE_TEXT = 'EDIT_TEMPLATE_TEXT';
export const EDIT_HTML_FIELD = 'EDIT_HTML_FIELD';
export const UPDATE_BASE_FIELD = 'UPDATE_BASE_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const CREATE_TEMPLATE = {
  PENDING: '@CREATE_TEMPLATE/PENDING',
  SUCCESS: '@CREATE_TEMPLATE/SUCCESS',
  ERROR: '@CREATE_TEMPLATE/ERROR',
};

export const UPDATE_COMPLEX_FIELD_TABLE = 'UPDATE_COMPLEX_FIELD_TABLE';
export const UPDATE_COMPLEX_FIELD_TEXT = 'UPDATE_COMPLEX_FIELD_TEXT';

export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';
export const REMOVE_ATTACHMENT = 'REMOVE_ATTACHMENT';
export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT';

export const CREATE_TABLE_COLUMN = 'CREATE_TABLE_COLUMN';
export const REMOVE_TABLE_COLUMN = 'REMOVE_TABLE_COLUMN';

export const CREATE_TEXT_OPTION = 'CREATE_TEXT_OPTION';

export const CREATE_FORM_DATA = 'CREATE_FORM_DATA';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';

/****************     VALIDATION *****************************/

export const SET_TEMPLATE_NAME_ERROR_MESSAGE =
  'SET_TEMPLATE_NAME_ERROR_MESSAGE';
export const CLEAR_TEMPLATE_NAME_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';

export const SET_TITLE_ERROR_MESSAGE = 'SET_TITLE_ERROR_MESSAGE';
export const CLEAR_TITLE_ERROR_MESSAGE = 'CLEAR_TITLE_ERROR_MESSAGE';

export const SET_COL_TITLE_ERROR_MESSAGE = 'SET_COL_TITLE_ERROR_MESSAGE';
export const CLEAR_COL_TITLE_ERROR_MESSAGE = 'CLEAR_COL_TITLE_ERROR_MESSAGE';

export const SET_TEXT_OPTIONS_ERROR_MESSAGE = 'SET_TEXT_OPTIONS_ERROR_MESSAGE';
export const CLEAR_TEXT_OPTIONS_ERROR_MESSAGE =
  'CLEAR_TEXT_OPTIONS_ERROR_MESSAGE';

export const SET_ATTACHMENT_ERROR_TEXT = 'SET_ATTACHMENT_ERROR_TEXT';
export const CLEAR_ATTACHMENT_ERROR_TEXT = 'CLEAR_ATTACHMENT_ERROR_TEXT';
